// All TypeScript types for Lumé.
// These mirror the Supabase database tables exactly.

// ─── Brand preferences ────────────────────────────────────────────────────────
export interface PreferredBrands {
  skin:   string[];
  hair:   string[];
  makeup: string[];
}

export type BudgetTier = 'budget' | 'mid' | 'premium';

export type BrandPhilosophy =
  | 'ingredient_focused'
  | 'natural_ayurvedic'
  | 'professional_salon'
  | 'luxury'
  | 'mass_market';

// ─── User ────────────────────────────────────────────────────────────────────
// Matches the public.users table.
export interface User {
  id:                     string;           // uuid — matches auth.users id
  display_name:           string | null;
  gender:                 'man' | 'woman' | 'other' | null;
  city:                   string | null;
  avatar_url:             string | null;
  referral_code:          string | null;
  referred_by:            string | null;    // uuid of referring user
  push_token:             string | null;
  notification_reminders: boolean;
  notification_routine:   boolean;
  last_scan_at:           string | null;    // ISO timestamp
  onboarding_complete:    boolean;
  age_range?:             '18-25' | '26-35' | '36-45' | '46-55' | '55+' | null;
  created_at:             string;           // ISO timestamp
  hair_profile:           HairProfile | null;
  hair_recommendations:   HairRecommendations | null;
  preferred_brands_v2:    PreferredBrands | null;
  budget?:                string;
}

// ─── Hair Profile ─────────────────────────────────────────────────────────────
// Stored in users.hair_profile JSONB column.
export interface HairProfile {
  hair_length:          'bald' | 'very_short' | 'short' | 'medium' | 'long';
  scalp_type:           'oily' | 'normal' | 'dry' | 'combination';
  scalp_concern?:       'dry_flaky' | 'oily_shiny' | 'sensitive' | 'none';
  sun_exposure?:        boolean;
  primary_concern?:     string[];
  texture?:             'straight' | 'wavy' | 'curly' | 'coily';
  wash_frequency?:      'daily' | 'every_2_3_days' | 'once_a_week' | 'less_than_weekly';
  oils_regularly?:      boolean;
  chemically_treated?:  'none' | 'color' | 'straightening' | 'perming' | 'multiple';
}

export function isBaldProfile(profile: HairProfile | null | undefined): boolean {
  return profile?.hair_length === 'bald';
}

// Stored in users.hair_recommendations JSONB column. Generated by Gemini
// from the user's hair profile — independent of the face scan.
export interface HairRecommendations {
  summary:               string;
  advice:                string;
  styles:                string[];
  styles_detailed?:      HairStyleRecommendation[];
  wash_frequency:        string;
  condition_explanation: string;
  wash_steps:            string[];
  weekly_treatment:      string;
  routine: {
    label:   string;
    product: string;
    level:   'simple' | 'balanced' | 'full';
    order:   number;
  }[];
  products:    ProductRecommendation[];
}

// ─── Recommendations ─────────────────────────────────────────────────────────
// Matches the recommendations JSONB column inside the scans table.

export interface HairStyleRecommendation {
  name:           string;
  why_face_shape: string;
  why_texture:    string;
  maintenance:    'low' | 'medium' | 'high';
  climate_note:   string | null;
  avoid:          boolean;
  avoid_reason?:  string;
}

// A product already matched from the catalogue and passed to Claude for reasons.
export interface MatchedProduct {
  category:    string;
  name:        string;
  brand:       string;
  why_good:    string;
  attributes:  string[];
  is_featured?: boolean;
}

// One product recommendation stored inside Recommendations — contains the
// matched product identity (name, brand) and Claude's personalised reason.
export interface ProductRecommendation {
  category:    string;
  name:        string;
  brand:       string;
  attributes?: string[];  // preserved for legacy scans
  reason:      string;
  match_score: number;
}

export interface RoutineStep {
  label:   string;
  product: string;
  level:   string;
  order:   number;
}

export interface SkinRecommendation {
  summary:     string;
  advice:      string;
  routine:     { morning: RoutineStep[]; evening: RoutineStep[] };
}

export interface BeardStyleItem {
  name:             string;
  maintenance:      'low' | 'medium' | 'high';
  why:              string;
  not_recommended?: boolean;
}

export interface BeardRecommendation {
  summary:       string;
  advice:        string;    // exact words to say to barber
  beard_styles?: BeardStyleItem[];
}

export interface MakeupRecommendation {
  summary:     string;
  advice:      string;
  techniques:  string[];
}

export interface Recommendations {
  skin:     SkinRecommendation;
  beard:    BeardRecommendation | null;    // men only
  makeup:   MakeupRecommendation | null;  // women only
  products: ProductRecommendation[];      // all matched products across sections
}

// ─── Scan ─────────────────────────────────────────────────────────────────────
// Matches the public.scans table.
export interface Scan {
  id:                string;    // uuid
  user_id:           string;    // uuid
  image_url:         string | null;

  // Face analysis from Gemini
  face_shape:        'oval' | 'round' | 'square' | 'heart' | 'oblong' | 'diamond' | null;
  skin_type:         'oily' | 'dry' | 'combination' | 'normal' | 'sensitive' | null;
  skin_concerns:     string[] | null;
  beard_density:     'none' | 'light' | 'medium' | 'heavy' | null;  // men only
  beard_condition:   string | null;
  brow_condition:    string | null;
  undereye:          string | null;
  fitzpatrick_scale?: number | null;
  skin_tone?:         string | null;
  skin_undertone?:    'warm' | 'cool' | 'neutral' | null;

  // Scores
  score_skin:        number | null;    // 0-100
  score_beard:       number | null;    // 0-100, null for women
  score_makeup:      number | null;    // 0-100, null for men
  score_overall:     number | null;    // average of applicable categories

  tier_label?:       string | null;    // kept for DB compatibility only — not used in UI

  // AI-generated advice from Claude Haiku
  recommendations:   Recommendations | null;

  stylist_mentioned: string | null;    // optional name/handle tagged by user
  share_count:       number;
  created_at:        string;           // ISO timestamp
}

// ─── Partial Scan ─────────────────────────────────────────────────────────────
// Represents the scan state after phase 1 (vision only) completes.
// All analysis fields are present; recommendations are null until phase 2 finishes.
export interface PartialScan {
  id:                string;
  user_id:           string;
  face_shape:        string | null;
  skin_type:         string | null;
  skin_concerns:     string[] | null;
  beard_density:     string | null;
  beard_condition:   string | null;
  brow_condition:    string | null;
  undereye:          string | null;
  fitzpatrick_scale: number | null;
  skin_tone:         string | null;
  skin_undertone:    string | null;
  score_skin:        number | null;
  score_beard:       number | null;
  score_makeup:      number | null;
  score_overall:     number | null;
  recommendations:   null;
  created_at:        string;
}

// ─── Shadow Stylist ───────────────────────────────────────────────────────────
// Matches the public.shadow_stylists table.
// These are stylists users mention who haven't signed up yet.
export interface ShadowStylist {
  id:               string;
  name:             string | null;
  instagram_handle: string | null;
  salon_name:       string | null;
  city:             string | null;
  mention_count:    number;
  mentioned_by:     string[];   // array of user uuids
  source:           string[];   // e.g. ['user_mention']
  outreach_status:  'none' | 'contacted' | 'onboarded';
  created_at:       string;
}

// ─── Waitlist ─────────────────────────────────────────────────────────────────
// Matches the public.waitlist table.
export interface Waitlist {
  id:         string;
  email:      string;
  city:       string | null;
  created_at: string;
}
