// Routine tab — daily grooming checklist + streak + progress calendar

import { useEffect, useState, useCallback } from 'react';
import {
  View, Text, StyleSheet, ScrollView, TouchableOpacity,
  TextInput, ActivityIndicator, RefreshControl, Dimensions,
} from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import * as Notifications from 'expo-notifications';
import { StatusBar } from 'expo-status-bar';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { supabase } from '../../lib/supabase';
import { Colors, Typography, Spacing, Radius } from '../../constants/theme';
import { GUEST_PROFILE_KEY } from '../_layout';
import type { Scan } from '../../types';

// ── Storage keys ─────────────────────────────────────────────────────────────
const STEPS_KEY  = '@lume/routine_steps';
const LOG_KEY    = '@lume/routine_log';
const STREAK_KEY = '@lume/routine_streak';

// ── Types ─────────────────────────────────────────────────────────────────────
interface RoutineStep {
  id:            string;
  text:          string;
  time:          'morning' | 'evening';
  autoGenerated: boolean;
}

interface StreakData {
  current:  number;
  best:     number;
  lastDate: string;
}

type DailyLog = Record<string, string[]>;

// ── Date helpers ──────────────────────────────────────────────────────────────
function todayStr(): string {
  return new Date().toISOString().slice(0, 10);
}

function isYesterday(dateStr: string): boolean {
  const yesterday = new Date();
  yesterday.setDate(yesterday.getDate() - 1);
  return dateStr === yesterday.toISOString().slice(0, 10);
}

function daysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString().slice(0, 10);
}

// ── Auto-generate steps from scan data ───────────────────────────────────────
function generateSteps(scan: Partial<Scan> | null): RoutineStep[] {
  const steps: RoutineStep[] = [
    { id: 'gen_cleanse_am',   text: 'Gentle cleanser',    time: 'morning', autoGenerated: true },
    { id: 'gen_moisturise',   text: 'Moisturiser',         time: 'morning', autoGenerated: true },
    { id: 'gen_spf',          text: 'SPF 30+',             time: 'morning', autoGenerated: true },
    { id: 'gen_cleanse_pm',   text: 'Cleanser',            time: 'evening', autoGenerated: true },
    { id: 'gen_night_moist',  text: 'Night moisturiser',   time: 'evening', autoGenerated: true },
  ];

  if (scan) {
    if (scan.skin_type === 'oily') {
      steps.splice(3, 0, { id: 'gen_toner', text: 'Toner', time: 'morning', autoGenerated: true });
    }
    if (scan.skin_type === 'dry') {
      steps.splice(3, 0, { id: 'gen_serum', text: 'Hydrating serum', time: 'morning', autoGenerated: true });
    }
    if (scan.hair_condition === 'dry' || scan.hair_condition === 'damaged') {
      steps.push({ id: 'gen_hair_oil', text: 'Hair oil (weekly)', time: 'evening', autoGenerated: true });
    }
    if (scan.beard_density === 'medium' || scan.beard_density === 'heavy') {
      steps.push({ id: 'gen_beard_oil', text: 'Beard oil', time: 'morning', autoGenerated: true });
    }
    if (scan.brow_shape) {
      steps.push({ id: 'gen_brow_gel', text: 'Brow gel', time: 'morning', autoGenerated: true });
    }
  }

  return steps;
}

// ── Notification helper ───────────────────────────────────────────────────────
async function scheduleRoutineReminder() {
  try {
    const { status } = await Notifications.getPermissionsAsync();
    if (status !== 'granted') return;

    const existing = await Notifications.getAllScheduledNotificationsAsync();
    const hasReminder = existing.some(n => n.content.data?.type === 'routine_reminder');

    if (!hasReminder) {
      await Notifications.scheduleNotificationAsync({
        content: {
          title: 'Lumé',
          body:  "Don't forget your grooming routine today!",
          data:  { type: 'routine_reminder' },
        },
        trigger: { hour: 8, minute: 0, repeats: true } as Notifications.DailyTriggerInput,
      });
    }
  } catch {
    // Notifications unavailable — ignore silently
  }
}

// ── Screen width for heatmap ──────────────────────────────────────────────────
const { width: SW } = Dimensions.get('window');
const CELL = Math.floor((SW - Spacing.lg * 2 - 6 * 4) / 7);

// ─────────────────────────────────────────────────────────────────────────────
export default function RoutineScreen() {
  const insets = useSafeAreaInsets();

  const [activeTab,      setActiveTab]      = useState<'routine' | 'progress'>('routine');
  const [steps,          setSteps]          = useState<RoutineStep[]>([]);
  const [completedToday, setCompletedToday] = useState<string[]>([]);
  const [streak,         setStreak]         = useState<StreakData>({ current: 0, best: 0, lastDate: '' });
  const [dailyLog,       setDailyLog]       = useState<DailyLog>({});
  const [scans,          setScans]          = useState<Scan[]>([]);
  const [loading,        setLoading]        = useState(true);
  const [refreshing,     setRefreshing]     = useState(false);

  const [editMode,       setEditMode]       = useState(false);
  const [addingMorning,  setAddingMorning]  = useState(false);
  const [addingEvening,  setAddingEvening]  = useState(false);
  const [newStepText,    setNewStepText]    = useState('');

  // ── Load everything on mount ────────────────────────────────────────────────
  const loadAll = useCallback(async () => {
    try {
      // 1. Load or generate steps
      const rawSteps = await AsyncStorage.getItem(STEPS_KEY);
      if (rawSteps) {
        setSteps(JSON.parse(rawSteps) as RoutineStep[]);
      } else {
        // Auto-generate from last scan
        const { data: { user } } = await supabase.auth.getUser();
        let lastScan: Partial<Scan> | null = null;

        if (user) {
          const { data } = await supabase
            .from('scans')
            .select('skin_type, hair_condition, beard_density, brow_shape')
            .eq('user_id', user.id)
            .order('created_at', { ascending: false })
            .limit(1)
            .single();
          lastScan = data ?? null;
        } else {
          const raw = await AsyncStorage.getItem(GUEST_PROFILE_KEY);
          if (raw) {
            const guest = JSON.parse(raw) as { gender?: string };
            lastScan = { beard_density: guest.gender === 'man' ? 'light' : undefined };
          }
        }

        const generated = generateSteps(lastScan);
        setSteps(generated);
        await AsyncStorage.setItem(STEPS_KEY, JSON.stringify(generated));
      }

      // 2. Load today's completions
      const rawLog = await AsyncStorage.getItem(LOG_KEY);
      const log: DailyLog = rawLog ? (JSON.parse(rawLog) as DailyLog) : {};
      setDailyLog(log);
      setCompletedToday(log[todayStr()] ?? []);

      // 3. Load & recalculate streak
      const rawStreak = await AsyncStorage.getItem(STREAK_KEY);
      const s: StreakData = rawStreak
        ? (JSON.parse(rawStreak) as StreakData)
        : { current: 0, best: 0, lastDate: '' };

      // If lastDate was yesterday and we have completions today, keep current
      // but don't auto-increment — only increment when a step is checked
      // If lastDate is before yesterday, reset current (streak broken)
      if (s.lastDate && s.lastDate !== todayStr() && !isYesterday(s.lastDate)) {
        s.current = 0;
        await AsyncStorage.setItem(STREAK_KEY, JSON.stringify(s));
      }
      setStreak(s);

      // 4. Load scan history for progress tab
      const { data: { user } } = await supabase.auth.getUser();
      if (user) {
        const { data } = await supabase
          .from('scans')
          .select('id, score_overall, created_at')
          .eq('user_id', user.id)
          .order('created_at', { ascending: true })
          .limit(10);
        if (data) setScans(data as Scan[]);
      }

      // 5. Schedule daily reminder
      await scheduleRoutineReminder();
    } catch (err) {
      console.error('[routine] Load error:', err instanceof Error ? err.message : String(err));
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, []);

  useEffect(() => { loadAll(); }, []);

  const onRefresh = () => { setRefreshing(true); loadAll(); };

  // ── Toggle step completion ──────────────────────────────────────────────────
  const toggleStep = useCallback(async (stepId: string) => {
    const today = todayStr();
    const rawLog = await AsyncStorage.getItem(LOG_KEY);
    const log: DailyLog = rawLog ? (JSON.parse(rawLog) as DailyLog) : {};
    const todayDone = log[today] ?? [];

    let newDone: string[];
    if (todayDone.includes(stepId)) {
      newDone = todayDone.filter(id => id !== stepId);
    } else {
      newDone = [...todayDone, stepId];

      // Update streak on first check of the day
      const rawStreak = await AsyncStorage.getItem(STREAK_KEY);
      const s: StreakData = rawStreak
        ? (JSON.parse(rawStreak) as StreakData)
        : { current: 0, best: 0, lastDate: '' };

      if (s.lastDate === today) {
        // Already counted — no change
      } else if (isYesterday(s.lastDate)) {
        s.current += 1;
        s.best = Math.max(s.current, s.best);
        s.lastDate = today;
      } else {
        s.current = 1;
        s.lastDate = today;
        if (s.best === 0) s.best = 1;
      }

      await AsyncStorage.setItem(STREAK_KEY, JSON.stringify(s));
      setStreak(s);
    }

    log[today] = newDone;
    await AsyncStorage.setItem(LOG_KEY, JSON.stringify(log));
    setDailyLog({ ...log });
    setCompletedToday(newDone);
  }, []);

  // ── Add / delete steps in edit mode ────────────────────────────────────────
  const addStep = useCallback(async (time: 'morning' | 'evening') => {
    const text = newStepText.trim();
    if (!text) return;
    const newStep: RoutineStep = {
      id:            `custom_${Date.now()}`,
      text,
      time,
      autoGenerated: false,
    };
    const updated = [...steps, newStep];
    setSteps(updated);
    await AsyncStorage.setItem(STEPS_KEY, JSON.stringify(updated));
    setNewStepText('');
    setAddingMorning(false);
    setAddingEvening(false);
  }, [steps, newStepText]);

  const deleteStep = useCallback(async (stepId: string) => {
    const updated = steps.filter(s => s.id !== stepId);
    setSteps(updated);
    await AsyncStorage.setItem(STEPS_KEY, JSON.stringify(updated));
  }, [steps]);

  // ── Derived values ──────────────────────────────────────────────────────────
  const morningSteps = steps.filter(s => s.time === 'morning');
  const eveningSteps = steps.filter(s => s.time === 'evening');
  const totalSteps   = steps.length;
  const doneCount    = completedToday.length;

  if (loading) {
    return (
      <View style={[st.screen, st.centre, { paddingTop: insets.top }]}>
        <ActivityIndicator color={Colors.gold} size="large" />
      </View>
    );
  }

  return (
    <View style={[st.screen, { paddingTop: insets.top }]}>
      <StatusBar style="light" />

      {/* Sub-tab bar */}
      <View style={st.subTabBar}>
        <TouchableOpacity
          style={[st.subTab, activeTab === 'routine' && st.subTabActive]}
          onPress={() => setActiveTab('routine')}
          activeOpacity={0.8}
        >
          <Text style={[st.subTabText, activeTab === 'routine' && st.subTabTextActive]}>
            Routine
          </Text>
        </TouchableOpacity>
        <TouchableOpacity
          style={[st.subTab, activeTab === 'progress' && st.subTabActive]}
          onPress={() => setActiveTab('progress')}
          activeOpacity={0.8}
        >
          <Text style={[st.subTabText, activeTab === 'progress' && st.subTabTextActive]}>
            Progress
          </Text>
        </TouchableOpacity>
      </View>

      {activeTab === 'routine' ? (
        <RoutineTab
          morningSteps={morningSteps}
          eveningSteps={eveningSteps}
          completedToday={completedToday}
          streak={streak}
          totalSteps={totalSteps}
          doneCount={doneCount}
          editMode={editMode}
          setEditMode={setEditMode}
          addingMorning={addingMorning}
          addingEvening={addingEvening}
          setAddingMorning={setAddingMorning}
          setAddingEvening={setAddingEvening}
          newStepText={newStepText}
          setNewStepText={setNewStepText}
          toggleStep={toggleStep}
          addStep={addStep}
          deleteStep={deleteStep}
          refreshing={refreshing}
          onRefresh={onRefresh}
          bottomPad={insets.bottom}
        />
      ) : (
        <ProgressTab
          dailyLog={dailyLog}
          completedToday={completedToday}
          totalSteps={totalSteps}
          scans={scans}
          refreshing={refreshing}
          onRefresh={onRefresh}
          bottomPad={insets.bottom}
        />
      )}
    </View>
  );
}

// ─── Routine sub-tab ──────────────────────────────────────────────────────────
interface RoutineTabProps {
  morningSteps:    RoutineStep[];
  eveningSteps:    RoutineStep[];
  completedToday:  string[];
  streak:          StreakData;
  totalSteps:      number;
  doneCount:       number;
  editMode:        boolean;
  setEditMode:     (v: boolean) => void;
  addingMorning:   boolean;
  addingEvening:   boolean;
  setAddingMorning:(v: boolean) => void;
  setAddingEvening:(v: boolean) => void;
  newStepText:     string;
  setNewStepText:  (v: string) => void;
  toggleStep:      (id: string) => void;
  addStep:         (time: 'morning' | 'evening') => void;
  deleteStep:      (id: string) => void;
  refreshing:      boolean;
  onRefresh:       () => void;
  bottomPad:       number;
}

function RoutineTab({
  morningSteps, eveningSteps, completedToday, streak,
  totalSteps, doneCount, editMode, setEditMode,
  addingMorning, addingEvening, setAddingMorning, setAddingEvening,
  newStepText, setNewStepText, toggleStep, addStep, deleteStep,
  refreshing, onRefresh, bottomPad,
}: RoutineTabProps) {
  const morningDone = morningSteps.filter(s => completedToday.includes(s.id)).length;
  const eveningDone = eveningSteps.filter(s => completedToday.includes(s.id)).length;
  const progress    = totalSteps > 0 ? doneCount / totalSteps : 0;

  return (
    <ScrollView
      contentContainerStyle={[st.content, { paddingBottom: bottomPad + Spacing.xxxl }]}
      showsVerticalScrollIndicator={false}
      refreshControl={<RefreshControl refreshing={refreshing} onRefresh={onRefresh} tintColor={Colors.gold} />}
    >
      {/* Header row */}
      <View style={st.headerRow}>
        <Text style={st.screenTitle}>Daily Routine</Text>
        <TouchableOpacity onPress={() => setEditMode(!editMode)} activeOpacity={0.7}>
          <Text style={st.editBtn}>{editMode ? 'Done' : 'Edit'}</Text>
        </TouchableOpacity>
      </View>

      {/* Streak card */}
      <View style={st.streakCard}>
        <View style={st.streakLeft}>
          <Text style={st.streakNum}>{streak.current}</Text>
          <Text style={st.streakLabel}>day streak</Text>
          <Text style={st.streakBest}>Best: {streak.best} days</Text>
        </View>
        <Text style={st.streakEmoji}>🔥</Text>
      </View>

      {/* Progress bar */}
      <View style={st.progressWrap}>
        <View style={st.progressTrack}>
          <View style={[st.progressFill, { width: `${Math.round(progress * 100)}%` }]} />
        </View>
        <Text style={st.progressText}>{doneCount}/{totalSteps} today</Text>
      </View>

      {/* Morning section */}
      <SectionLabel label="Morning" done={morningDone} total={morningSteps.length} />
      <View style={st.card}>
        {morningSteps.map((step, idx) => (
          <View key={step.id}>
            {idx > 0 && <View style={st.divider} />}
            <StepRow
              step={step}
              done={completedToday.includes(step.id)}
              editMode={editMode}
              onToggle={() => toggleStep(step.id)}
              onDelete={() => deleteStep(step.id)}
            />
          </View>
        ))}
        {editMode && (
          addingMorning ? (
            <View style={st.addInputRow}>
              <TextInput
                style={st.addInput}
                placeholder="Step name…"
                placeholderTextColor={Colors.textTertiary}
                value={newStepText}
                onChangeText={setNewStepText}
                onSubmitEditing={() => addStep('morning')}
                returnKeyType="done"
                autoFocus
              />
              <TouchableOpacity onPress={() => addStep('morning')} style={st.addConfirm}>
                <Text style={st.addConfirmText}>Add</Text>
              </TouchableOpacity>
            </View>
          ) : (
            <TouchableOpacity style={st.addRow} onPress={() => { setNewStepText(''); setAddingMorning(true); }}>
              <Text style={st.addRowText}>+ Add morning step</Text>
            </TouchableOpacity>
          )
        )}
      </View>

      {/* Evening section */}
      <SectionLabel label="Evening" done={eveningDone} total={eveningSteps.length} />
      <View style={st.card}>
        {eveningSteps.map((step, idx) => (
          <View key={step.id}>
            {idx > 0 && <View style={st.divider} />}
            <StepRow
              step={step}
              done={completedToday.includes(step.id)}
              editMode={editMode}
              onToggle={() => toggleStep(step.id)}
              onDelete={() => deleteStep(step.id)}
            />
          </View>
        ))}
        {editMode && (
          addingEvening ? (
            <View style={st.addInputRow}>
              <TextInput
                style={st.addInput}
                placeholder="Step name…"
                placeholderTextColor={Colors.textTertiary}
                value={newStepText}
                onChangeText={setNewStepText}
                onSubmitEditing={() => addStep('evening')}
                returnKeyType="done"
                autoFocus
              />
              <TouchableOpacity onPress={() => addStep('evening')} style={st.addConfirm}>
                <Text style={st.addConfirmText}>Add</Text>
              </TouchableOpacity>
            </View>
          ) : (
            <TouchableOpacity style={st.addRow} onPress={() => { setNewStepText(''); setAddingEvening(true); }}>
              <Text style={st.addRowText}>+ Add evening step</Text>
            </TouchableOpacity>
          )
        )}
      </View>
    </ScrollView>
  );
}

// ─── Progress sub-tab ─────────────────────────────────────────────────────────
interface ProgressTabProps {
  dailyLog:       DailyLog;
  completedToday: string[];
  totalSteps:     number;
  scans:          Scan[];
  refreshing:     boolean;
  onRefresh:      () => void;
  bottomPad:      number;
}

function ProgressTab({ dailyLog, totalSteps, scans, refreshing, onRefresh, bottomPad }: ProgressTabProps) {
  const today = todayStr();

  // Build 28-day grid (day 27 = oldest, day 0 = today)
  const cells = Array.from({ length: 28 }, (_, i) => {
    const dateStr = daysAgo(27 - i);
    const done    = (dailyLog[dateStr] ?? []).length;
    return { dateStr, done };
  });

  const completedDays   = cells.filter(c => c.done > 0).length;
  const consistencyPct  = Math.round((completedDays / 28) * 100);

  // Score bars
  const maxScore = scans.length > 0 ? Math.max(...scans.map(s => s.score_overall ?? 0)) : 100;

  return (
    <ScrollView
      contentContainerStyle={[st.content, { paddingBottom: bottomPad + Spacing.xxxl }]}
      showsVerticalScrollIndicator={false}
      refreshControl={<RefreshControl refreshing={refreshing} onRefresh={onRefresh} tintColor={Colors.gold} />}
    >
      <Text style={st.screenTitle}>Progress</Text>

      {/* 28-day heatmap */}
      <Text style={st.sectionLabel}>28-DAY CONSISTENCY</Text>
      <View style={st.card}>
        <View style={st.heatmapGrid}>
          {cells.map((cell, idx) => {
            const isToday   = cell.dateStr === today;
            const hasData   = cell.done > 0;
            return (
              <View
                key={idx}
                style={[
                  st.heatCell,
                  { width: CELL, height: CELL },
                  hasData   && st.heatCellDone,
                  isToday   && st.heatCellToday,
                ]}
              />
            );
          })}
        </View>

        {/* Stats row */}
        <View style={st.heatStats}>
          <View style={st.heatStat}>
            <Text style={st.heatStatNum}>{completedDays}</Text>
            <Text style={st.heatStatLabel}>days completed</Text>
          </View>
          <View style={st.statDivider} />
          <View style={st.heatStat}>
            <Text style={st.heatStatNum}>{consistencyPct}%</Text>
            <Text style={st.heatStatLabel}>consistency</Text>
          </View>
        </View>
      </View>

      {/* Score trend */}
      <Text style={st.sectionLabel}>SCORE TREND</Text>
      <View style={st.card}>
        {scans.length >= 2 ? (
          <View style={st.barsWrap}>
            {scans.map((scan, idx) => {
              const score   = scan.score_overall ?? 0;
              const barH    = Math.max(4, Math.round((score / (maxScore || 100)) * 80));
              const isLast  = idx === scans.length - 1;
              const dateLabel = scan.created_at
                ? new Date(scan.created_at).toLocaleDateString('en', { day: 'numeric', month: 'short' })
                : '';
              return (
                <View key={scan.id} style={st.barCol}>
                  <Text style={[st.barScore, isLast && { color: Colors.gold }]}>{score}</Text>
                  <View style={st.barTrack}>
                    <View
                      style={[
                        st.barFill,
                        { height: barH },
                        isLast && { backgroundColor: Colors.gold },
                      ]}
                    />
                  </View>
                  <Text style={st.barDate}>{dateLabel}</Text>
                </View>
              );
            })}
          </View>
        ) : (
          <Text style={st.emptyMsg}>
            Scan again in 7 days to see your progress
          </Text>
        )}
      </View>

      {/* Legend */}
      <View style={st.legend}>
        <View style={[st.legendDot, { backgroundColor: Colors.gold }]} />
        <Text style={st.legendText}>Routine completed</Text>
        <View style={[st.legendDot, { backgroundColor: Colors.surface2, marginLeft: Spacing.md }]} />
        <Text style={st.legendText}>No activity</Text>
      </View>
    </ScrollView>
  );
}

// ─── Section label row ────────────────────────────────────────────────────────
function SectionLabel({ label, done, total }: { label: string; done: number; total: number }) {
  return (
    <View style={st.sectionRow}>
      <Text style={st.sectionLabel}>{label.toUpperCase()}</Text>
      <Text style={st.sectionCount}>{done}/{total} done</Text>
    </View>
  );
}

// ─── Step row ─────────────────────────────────────────────────────────────────
function StepRow({ step, done, editMode, onToggle, onDelete }: {
  step:     RoutineStep;
  done:     boolean;
  editMode: boolean;
  onToggle: () => void;
  onDelete: () => void;
}) {
  return (
    <View style={st.stepRow}>
      {editMode && (
        <Text style={st.dragHandle}>☰</Text>
      )}
      <TouchableOpacity
        style={[st.checkbox, done && st.checkboxDone]}
        onPress={onToggle}
        activeOpacity={0.7}
      >
        {done && <Text style={st.checkmark}>✓</Text>}
      </TouchableOpacity>
      <Text style={[st.stepText, done && st.stepTextDone]}>{step.text}</Text>
      {editMode && (
        <TouchableOpacity onPress={onDelete} style={st.deleteBtn} hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}>
          <Text style={st.deleteX}>✕</Text>
        </TouchableOpacity>
      )}
    </View>
  );
}

// ─── Styles ───────────────────────────────────────────────────────────────────
const st = StyleSheet.create({
  screen:  { flex: 1, backgroundColor: Colors.background },
  centre:  { alignItems: 'center', justifyContent: 'center' },
  content: { paddingHorizontal: Spacing.lg, paddingTop: Spacing.md },

  // Sub-tab bar
  subTabBar: {
    flexDirection:   'row',
    backgroundColor: Colors.surface,
    marginHorizontal: Spacing.lg,
    marginTop:       Spacing.md,
    marginBottom:    Spacing.md,
    borderRadius:    Radius.pill,
    padding:         3,
    borderWidth:     1,
    borderColor:     Colors.border,
  },
  subTab: {
    flex:           1,
    paddingVertical: 8,
    alignItems:     'center',
    borderRadius:   Radius.pill,
  },
  subTabActive: { backgroundColor: Colors.gold },
  subTabText:   { fontSize: Typography.size.sm, color: Colors.textSecondary, fontWeight: '500' },
  subTabTextActive: { color: Colors.background, fontWeight: '700' },

  // Header row
  headerRow: {
    flexDirection:  'row',
    alignItems:     'center',
    justifyContent: 'space-between',
    marginBottom:   Spacing.md,
  },
  screenTitle: {
    fontFamily:   Typography.serif,
    fontSize:     Typography.size.xl,
    color:        Colors.cream,
    marginBottom: Spacing.md,
  },
  editBtn: {
    fontSize:  Typography.size.base,
    color:     Colors.gold,
    fontWeight:'600',
  },

  // Streak card
  streakCard: {
    flexDirection:   'row',
    alignItems:      'center',
    justifyContent:  'space-between',
    backgroundColor: Colors.surface,
    borderRadius:    Radius.card,
    borderWidth:     1,
    borderColor:     Colors.border,
    padding:         Spacing.lg,
    marginBottom:    Spacing.md,
  },
  streakLeft:  { gap: 2 },
  streakNum:   { fontFamily: Typography.serif, fontSize: 40, color: Colors.cream, lineHeight: 44 },
  streakLabel: { fontSize: Typography.size.sm, color: Colors.textSecondary },
  streakBest:  { fontSize: Typography.size.xs, color: Colors.textTertiary, marginTop: 2 },
  streakEmoji: { fontSize: 36 },

  // Progress bar
  progressWrap: { marginBottom: Spacing.xl },
  progressTrack: {
    height:          6,
    backgroundColor: Colors.border,
    borderRadius:    3,
    overflow:        'hidden',
    marginBottom:    4,
  },
  progressFill: {
    height:          6,
    backgroundColor: Colors.gold,
    borderRadius:    3,
  },
  progressText: { fontSize: Typography.size.xs, color: Colors.textSecondary, textAlign: 'right' },

  // Section header
  sectionRow: {
    flexDirection:  'row',
    alignItems:     'center',
    justifyContent: 'space-between',
    marginBottom:   Spacing.xs,
    marginTop:      Spacing.sm,
  },
  sectionLabel: {
    fontSize:      Typography.size.xs,
    color:         Colors.gold,
    letterSpacing: 6,
    textTransform: 'uppercase',
    marginBottom:  Spacing.sm,
    marginTop:     Spacing.sm,
  },
  sectionCount: { fontSize: Typography.size.xs, color: Colors.gold },

  // Card
  card: {
    backgroundColor: Colors.surface,
    borderRadius:    Radius.card,
    borderWidth:     1,
    borderColor:     Colors.border,
    marginBottom:    Spacing.md,
    overflow:        'hidden',
  },
  divider: { height: 1, backgroundColor: Colors.border, marginHorizontal: Spacing.md },

  // Step row
  stepRow: {
    flexDirection: 'row',
    alignItems:    'center',
    padding:       Spacing.md,
    gap:           Spacing.sm,
  },
  checkbox: {
    width:        22, height:       22,
    borderRadius: 5,  borderWidth:  2,
    borderColor:  Colors.border,
    alignItems:   'center', justifyContent: 'center',
  },
  checkboxDone: { backgroundColor: Colors.gold, borderColor: Colors.gold },
  checkmark:    { color: Colors.background, fontSize: 13, fontWeight: '700' },
  stepText:     { flex: 1, fontSize: Typography.size.base, color: Colors.cream },
  stepTextDone: { color: Colors.textSecondary, textDecorationLine: 'line-through' },
  dragHandle:   { fontSize: 16, color: Colors.textTertiary, marginRight: 2 },
  deleteBtn:    { padding: 4 },
  deleteX:      { fontSize: 14, color: Colors.danger },

  // Add step
  addRow: { padding: Spacing.md, alignItems: 'center' },
  addRowText: { fontSize: Typography.size.sm, color: Colors.gold },
  addInputRow: {
    flexDirection: 'row', alignItems: 'center',
    padding: Spacing.sm, gap: Spacing.sm,
    borderTopWidth: 1, borderTopColor: Colors.border,
  },
  addInput: {
    flex:              1,
    backgroundColor:   Colors.surface2,
    borderRadius:      Radius.input,
    paddingHorizontal: Spacing.sm,
    paddingVertical:   8,
    fontSize:          Typography.size.base,
    color:             Colors.cream,
  },
  addConfirm: {
    backgroundColor: Colors.gold,
    borderRadius:    Radius.input,
    paddingHorizontal: Spacing.md,
    paddingVertical:   8,
  },
  addConfirmText: { color: Colors.background, fontWeight: '600', fontSize: Typography.size.sm },

  // Heatmap
  heatmapGrid: {
    flexDirection: 'row', flexWrap: 'wrap',
    gap:           4,
    padding:       Spacing.md,
  },
  heatCell: {
    borderRadius:    3,
    backgroundColor: Colors.surface2,
  },
  heatCellDone:  { backgroundColor: Colors.gold },
  heatCellToday: { borderWidth: 2, borderColor: Colors.gold },

  heatStats: {
    flexDirection:  'row',
    alignItems:     'center',
    justifyContent: 'center',
    paddingVertical: Spacing.md,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
    gap:            Spacing.xl,
  },
  heatStat:     { alignItems: 'center' },
  heatStatNum:  { fontFamily: Typography.serif, fontSize: Typography.size.xl, color: Colors.cream },
  heatStatLabel:{ fontSize: Typography.size.xs, color: Colors.textSecondary, marginTop: 2 },
  statDivider:  { width: 1, height: 32, backgroundColor: Colors.border },

  // Score bars
  barsWrap: {
    flexDirection:  'row',
    alignItems:     'flex-end',
    justifyContent: 'space-around',
    padding:        Spacing.md,
    paddingTop:     Spacing.lg,
    minHeight:      120,
  },
  barCol:   { alignItems: 'center', gap: 4, flex: 1 },
  barScore: { fontSize: Typography.size.xs, color: Colors.textSecondary },
  barTrack: {
    width:           24, height:          80,
    backgroundColor: Colors.surface2,
    borderRadius:    4,
    justifyContent:  'flex-end',
    overflow:        'hidden',
  },
  barFill:  { width: 24, backgroundColor: Colors.textTertiary, borderRadius: 4 },
  barDate:  { fontSize: 9, color: Colors.textTertiary, textAlign: 'center' },
  emptyMsg: {
    fontSize:  Typography.size.sm, color: Colors.textSecondary,
    textAlign: 'center', padding: Spacing.xl, lineHeight: 20,
  },

  // Legend
  legend: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    gap: Spacing.xs, marginTop: Spacing.sm,
  },
  legendDot:  { width: 10, height: 10, borderRadius: 2 },
  legendText: { fontSize: Typography.size.xs, color: Colors.textSecondary },

  surface2: { backgroundColor: Colors.surface2 },
});
